project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

"files": [
  {
    source: "build/src/fw/tintin.pot",
    translation: "resources/normal/base/lang/%locale_with_region%/tintin.po"
  }
]